### ISSUE TITLE
NWIS data retrieval enhancement ideas

### ISSUE THREAD

**Issue by rsignell-usgs** [cheginit/pygeohydro#75]
It would be great to be able to set some parameter to ensure that the retrieved NWIS data are in UTC.  

Also it would be nice to have the ability to return the data (along with metadata such as units!) as an xarray dataset instead of a pandas dataframe. 

There is an [example NWIS code here](https://github.com/dnowacki-usgs/nwis) by @dnowacki-usgs that optionally returns an xarray dataset.

**Comment by cheginit** [comment]
Thanks for these good suggestions. I implemented them and updated [README](https://github.com/cheginit/pygeohydro/blob/main/README.rst) and the NWIS example [notebook](https://github.com/cheginit/HyRiver-examples/blob/main/notebooks/nwis.ipynb). Please take a look, give them a try, and let me know what you think.

**Comment by rsignell-usgs** [comment]
@cheginit , I just tried the lastest from master, and it worked great!
Thanks so much for implementing this!

**Comment by cheginit** [comment]
Great. Thanks!

**Comment by rsignell-usgs** [comment]
@cheginit , I just realized that if I requested 6000 stations, I would get 6000 variables.   It would be better if the stations were a new dimension (e.g. "station_id" or "feature_id") and we also had a "station_id" or "feature_id" variable that contained the name (character or int, I guess).  Would that be difficult?   Should I submit a new ticket?

**Comment by cheginit** [comment]
@rsignell-usgs I actually thought about this. The issue with this approach is that I have to include all station-specific attrs such as station name, lon, lat, etc as a new coordinate. So there is going to be too many dims. At the moment each station has 9 attributes, for example:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/13016644/144926919-f9e437b1-5978-4194-a41b-0e8aa8c654a1.png">

My initial approach looks like this:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/13016644/144927320-306692d5-dbdb-4836-8694-dd44e4333eac.png">

But at the end I just went with the simplest solution to keep all the attrs.

I am open to suggestions. Having time and station ID as dims is more in line with `xarray` but then we end up with too many dims. One way would be to just keep lon, lat and alt and drop the rest.

**Comment by cheginit** [comment]
After some thinking, I came up with a solution, all attrs as variables:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/13016644/144934396-cc7ff206-5a5f-4378-8f27-8c0f35f4771f.png">

There's no need for submitting a new feature. I will reference this issue.

Let me know what you think about this approach.

**Comment by rsignell-usgs** [comment]
@cheginit, that's a great idea!!!  Love it!

**Comment by cheginit** [comment]
Great! I'll probably release a new version late Dec. Till then, you can use it by installing from the main branch.
