### ISSUE TITLE
Allow access to NWIS Instantaneous values?

### ISSUE THREAD

**Issue by rsignell-usgs** [cheginit/pygeohydro#77]
It appears that there is only support for daily values from NWIS.   
Could the instantaneous NWIS values be optionally supported as well?
cc @jmccreight

**Comment by cheginit** [comment]
NWIS supports it. I added support for `iv` in the `xarray` commit:

```python
from pygeohydro import NWIS

nwis = NWIS()
qobs = nwis.get_streamflow("01646500", ("2005-01-01 12:00", "2005-01-12 15:00"), freq="iv")
```

If you've installed `pygeohydro` from the main branch you should be able to use this new feature.

**Comment by rsignell-usgs** [comment]
Woohoo!  Thanks @cheginit!
