### ISSUE TITLE
Handling server disconnects

### ISSUE THREAD

**Issue by kovar-ursa** [cheginit/pygeohydro#84]
I need to run millions of points against the new `gh.nlcd_bycoords`. During a recent run, the server disconnected:

```
  File "/home/kovar/anaconda3/envs/a50-dev/lib/python3.9/site-packages/aiohttp/c
lient.py", line 559, in _request
    await resp.start(conn)
  File "/home/kovar/anaconda3/envs/a50-dev/lib/python3.9/site-packages/aiohttp/c
lient_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/kovar/anaconda3/envs/a50-dev/lib/python3.9/site-packages/aiohttp/s
treams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

Questions:

1) Should pygeohydro handle this more gracefully or:
2) Is it up to me to handle it and, if so, how?
3) I need to rerun this, and many other collections of points. Am I abusing the server? Is the a way to do this locally?

Thank you.

-David

**Comment by cheginit** [comment]
Handling these types of errors should be done by the user. You can simply use `try-except` block to catch the exception and deal with it in a way that fits your purpose.

In your case, it's much better to get the data within the bounding box of you area of interest using `nlcd.bygeom` and then simply using [`xarray.interp`](https://xarray.pydata.org/en/stable/generated/xarray.DataArray.interp.html) to get the data with the `nearest` method for your points of interest. PyGeoHydro handles large areas by creating chunked `xarray.Dataset`s. So you should be able to use it even for large areas. The good thing about this approach is that you need to run `nlcd.bygeom` once. Afterward, you can just interpolate it for your points of interest as many times as you want and get the results quickly. You can take a look at the way that I do it in [`nlcd_bycoords`](https://github.com/cheginit/pygeohydro/blob/main/pygeohydro/pygeohydro.py#L463-L466) to get an idea of how you can implement it for your application.

**Comment by kovar-ursa** [comment]
Thank you!
