### ISSUE TITLE
Is there a way to specify the temp folder for pygeohydro.ssebopeta_bygeom()?

### ISSUE THREAD

**Issue by Flash-Of-Thunder** [cheginit/pygeohydro#89]
Hello,

Is there a way to specify the folder that AET nc files are being downloaded/unzipped to? Apologies if this is in the documentation but I wasn't seeing it. 

Kind Regards,

Samson

**Comment by cheginit** [comment]
No. It's not possible. The function detects the system's temp folder automatically based on the operating system. Why do you want to specify the temp folder?

**Comment by Flash-Of-Thunder** [comment]
Thanks for the information! Not sure it would have made a huge (any) difference.... the reason is I'm running ssebopeta_bygeom on a cluster and part of cluster has faster read/write speeds than where the temp file is located (at least this is what I assumed is meant when my admin says a certain directory is faster).

**Comment by cheginit** [comment]
Right, most probably download speed from the server is the bottleneck.
