### ISSUE TITLE
Did something change with NWIS?

### ISSUE THREAD

**Issue by rsignell-usgs** [cheginit/pygeohydro#99]
**What happened**:
my NWIS example stopped working

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```
from pygeohydro import NWIS

nwis = NWIS()

start = '1979-02-01T01:00:00'
stop =  '2020-12-31T23:00:00'

sta = ['USGS-01030350', 'USGS-01030500']

ds_obs = nwis.get_streamflow(sta, (start,stop), to_xarray=True)
```

I tried pygeohydro versions 0.13.0 and 0.13.1

**Comment by rsignell-usgs** [comment]
Oh jeez, my station names have 'USGS' in them.   Must have deleted the cell that stripped those.  :(
from pygeohydro import NWIS
```
nwis = NWIS()

start = '1979-02-01T01:00:00'
stop =  '2020-12-31T23:00:00'

sta = ['01030350', '01030500']

ds_obs = nwis.get_streamflow(sta, (start,stop), to_xarray=True)
```
works fine.   My bad.

**Comment by cheginit** [comment]
@rsignell-usgs I had to release a new version (0.13.2), so I included the latest commit that takes care of striping the USGS part and adding 0 padding, if necessary.

**Comment by rsignell-usgs** [comment]
Nice!  Thanks @cheginit !
